version: 0.0
os: linux

files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu   # Ubuntu server असल्यामुळे

  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: root
